name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  ci_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build app
        run: npm run build
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/

  infra_provision:
    runs-on: ubuntu-latest
    needs: ci_build
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        run: terraform plan
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
        
      - name: Get EC2 IP
        id: ec2_ip
        run: echo "ip=$(terraform output -raw ec2_ip)" >> $GITHUB_OUTPUT
        
    outputs:
      ec2_ip: ${{ steps.ec2_ip.outputs.ip }}

  app_deploy:
    runs-on: ubuntu-latest
    needs: [ci_build, infra_provision]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Setup SSH key from Parameter Store
        run: |
          mkdir -p ~/.ssh
          aws ssm get-parameter --name "/ec2/ssh-key/private" --with-decryption --query 'Parameter.Value' --output text > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ needs.infra_provision.outputs.ec2_ip }} >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2
        run: |
          scp -r dist/* ec2-user@${{ needs.infra_provision.outputs.ec2_ip }}:/tmp/
          ssh ec2-user@${{ needs.infra_provision.outputs.ec2_ip }} '
            sudo rm -rf /var/www/html/*
            sudo mv /tmp/* /var/www/html/
            sudo systemctl restart nginx
          '
